[package]
name = "hex-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
string-interner = "0.18.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
expect-test = "1.5"

[profile.release]
debug = true
